#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapimachinefailure-deployment
spec:
  selector:
    matchLabels:
      app: fastapimachinefailure-server
  replicas: 1
  template:
    metadata:
      labels:
        app: fastapimachinefailure-server
    spec:
      containers:
      - name: fastapimachinefailure-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/bryanvre/fastapimachinefailure:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: fastapimachinefailure-service
  name: fastapimachinefailure-service
spec:
  ports:
  - port: 300
    targetPort: 80
  selector:
    app: fastapimachinefailure-server
  type: LoadBalancer